### ISSUE TITLE
While importing "app", an ImportError was raised

### ISSUE THREAD

**Issue by udayansarma** [rebremer/ms-identity-python-webapp-sqldb#1]
I cloned this repo, changed the values in the app_config.py. Getting the following error 

C:\Users\udsarm\source\repos\ms-identity-python-webapp-backend>flask run --host localhost --port 5000
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "C:\Users\udsarm\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "C:\Users\udsarm\source\repos\ms-identity-python-webapp-backend\app.py", line 14, in <module>
    Session(app)
  File "C:\Users\udsarm\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_session\__init__.py", line 54, in __init__
    self.init_app(app)
  File "C:\Users\udsarm\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_session\__init__.py", line 61, in init_app
    app.session_interface = self._get_interface(app)
  File "C:\Users\udsarm\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_session\__init__.py", line 90, in _get_interface
    session_interface = FileSystemSessionInterface(
  File "C:\Users\udsarm\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_session\sessions.py", line 313, in __init__
    from flask_caching.backends.filesystem import FileSystemCache
ModuleNotFoundError: No module named 'flask_caching.backends.filesystem'

![error](https://user-images.githubusercontent.com/2105806/150587691-d7dad47e-287d-4501-9304-fef03cc1c8cb.png)

**Comment by udayansarma** [comment]
I don't have the same problem if I upgrade flask-session~=0.4.0

**Comment by Sakshi9119** [comment]
Hey!
Have you resolved the problem?

**Comment by rebremer** [comment]
@udayansarma , @Sakshi9119 , I updated requirements.txt, can you check? Please create a virtual environment first before testing to prevent dependencies issues. In requirements.txt you can find a link how to setup a virtual environment

**Comment by Sakshi9119** [comment]
Hey!
Thanks alot for your help!
I'll check it out.
